#!/usr/bin/env bash
# -*-  Mode: Shell-script -*-
# builder --- ConfD Example buider

set -eo pipefail; [[ "$TRACE" ]] && set -x

# builder ends here
main() {
    {
        cd $1
        pwd
        make clean all
        mkdir /build-result
        cp -f $(find . -maxdepth 1 -type f -executable) /build-result
    } >&2

    [[ $STDOUT ]] && tar czf - -C / build-result
}

main "$@"
