#!/usr/bin/env bash
# -*-  Mode: Shell-script -*-
# builder --- ConfD App builder

set -eo pipefail; [[ "$TRACE" ]] && set -x

main() {
    {
        cd $1
        make clean all
        mkdir /build-result
        cp -f $(find . -maxdepth 1 -type f -executable) /build-result
        [ -f confd.conf ] && cp *.fxs confd.conf ssh-keydir/* confd-cdb/aaa_init.xml /build-result
        [ -f /build-result/confd.conf ] && sed -i 's:  <loadPath>:  <!-- Allow IPC connections from non-localhost clinets -->\n  <confdIpcAddress>\n    <ip>0.0.0.0</ip>\n  </confdIpcAddress>\n\n  <!-- The IPC access token ensures that only clients that know the token\n       can connect to the IPC port. -->\n  <confdIpcAccessCheck>\n    <enabled>true</enabled>\n    <filename>/confd/secrets/access.txt</filename>\n  </confdIpcAccessCheck>\n\n  <loadPath>:;s:<sshServerKeyDir>./ssh-keydir</sshServerKeyDir>:<sshServerKeyDir>/confd/secrets</sshServerKeyDir>:' /build-result/confd.conf
    } >&2

    [[ $STDOUT ]] && tar czf - -C / build-result
}

main "$@"

# builder ends here
